const fs=require('fs'),path=require('path'),cp=require('child_process'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),out=path.resolve(root,'../resultados/backup'),base='http://127.0.0.1:8099';process.env.MCF_TEST_URL=base;const {Client}=require('./multiusuario/client.cjs');
const db=sql=>cp.execFileSync('C:/xampp/mysql/bin/mysql.exe',['--no-defaults','-h','127.0.0.1','-P','3307','-u','root','--batch','--skip-column-names','mcf_reports_test'],{input:sql,encoding:'utf8'}).trim();
let server,n=0;const ok=(v,label)=>{assert.ok(v,label);n++;};
const preview=p=>p.text.match(/name="token" value="([a-f0-9]+)"/)?.[1];
async function upload(c,data){const form=new FormData();form.set('acao','verificar');form.set('mcf_csrf',c.csrf);form.set('backup',new Blob([JSON.stringify(data)],{type:'application/json'}),'teste.json');const r=await fetch(base+'/views/backup.php',{method:'POST',headers:{cookie:c.cookie},body:form});return {status:r.status,text:await r.text()};}
(async()=>{
  fs.mkdirSync(out,{recursive:true});fs.mkdirSync(path.join(out,'sessions'),{recursive:true});
  cp.execFileSync(process.execPath,[path.join(__dirname,'relatorios-reset.cjs')],{stdio:'inherit'});
  db('CREATE TABLE usuario_modulos(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,usuario_id INT NOT NULL,modulo VARCHAR(50) NOT NULL,habilitado TINYINT(1) NOT NULL DEFAULT 1,UNIQUE KEY uk_usuario_modulo(usuario_id,modulo),FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE) ENGINE=InnoDB');
  db("INSERT INTO usuarios(id,email,senha,status_assinatura,data_expiracao) SELECT 3,'gama@example.test',senha,'ativo','2099-12-31' FROM usuarios WHERE id=1; INSERT INTO compras(id,usuario_id,nome,categoria,valor_total,total_parcelas,data_compra,origem) VALUES(501,1,'COMPRA_ALFA','pessoal',123.45,1,'2026-09-01','manual'); INSERT INTO cartoes(usuario_id,compra_id,data,valor,parcela,paga) VALUES(1,501,'2026-09-01',123.45,1,0); INSERT INTO corretoras(id,usuario_id,nome) VALUES(501,1,'ALFA'); INSERT INTO corretora_taxas(usuario_id,corretora_id,nome_taxa,percentual) VALUES(1,501,'TAXA',0.01234); INSERT INTO operacoes(usuario_id,corretora_id,data,acao,quantidade,total_compra,total_venda,lucro_final) VALUES(1,501,'2026-09-01','TEST3',10,100,120,20); INSERT INTO contas_financeiras(id,usuario_id,nome,tipo,saldo_inicial,data_saldo_inicial) VALUES(501,1,'CONTA_ALFA','corrente',50,'2026-01-01'); INSERT INTO movimentacoes_financeiras(usuario_id,conta_id,tipo,data,descricao,valor,origem_modulo,origem_id) VALUES(1,501,'entrada','2026-09-20','RENDA',1111,'receita',101); INSERT INTO investimentos_internacionais(usuario_id,ticker,tipo_ativo,quantidade,valor_unitario,valor_investido,data,tipo_operacao) VALUES(1,'BTC','cripto',0.00000001,123456.78912345,0.00123457,'2026-09-01','compra');");
  server=cp.spawn('C:/xampp/php/php.exe',['-d','session.save_path='+path.join(out,'sessions'),'-S','127.0.0.1:8099','-t',root,path.join(__dirname,'multiusuario/router.php')],{env:{...process.env,MCF_DB_HOST:'127.0.0.1',MCF_DB_PORT:'3307',MCF_DB_NAME:'mcf_reports_test',MCF_SESSION_NAME:'MCFREPORTTEST'},windowsHide:true,stdio:['ignore',fs.openSync(path.join(out,'server.log'),'a'),fs.openSync(path.join(out,'server.log'),'a')]});
  db("INSERT INTO usuario_modulos(usuario_id,modulo,habilitado) VALUES(1,'analise',0)");
  for(let i=0;i<30;i++){try{await fetch(base);break;}catch{await new Promise(r=>setTimeout(r,100));}}
  const anon=new Client(),a=new Client(),b=new Client(),g=new Client();ok((await anon.req('/views/backup.php')).status===401,'anônimo');for(const [c,email] of [[a,'alfa@example.test'],[b,'beta@example.test'],[g,'gama@example.test']]){await c.login(email);await c.req('/views/backup.php');}
  ok((await a.req('/views/configuracao.php')).text.includes('Backup da minha conta'),'atalho');
  let p=await a.req('/views/backup.php',{acao:'baixar',mcf_csrf:'errado'});ok(p.status===403,'csrf');
  p=await a.req('/views/backup.php',{acao:'baixar',mcf_csrf:a.csrf,usuario_id:'2'});ok(p.status===200,'download');const backup=JSON.parse(p.text);ok(backup.usuario_origem===1,'ator próprio');ok(!p.text.includes('BETA_PRIVADO'),'isolamento');ok(!p.text.includes('senha')&&!p.text.includes('token_hash'),'sem credenciais');ok(backup.tabelas.investimentos_internacionais[0].quantidade==='0.00000001','precisão');fs.writeFileSync(path.join(out,'backup-ficticio.json'),p.text);
  let bad=structuredClone(backup);bad.tabelas.contas[0].usuario_id=2;ok((await upload(g,bad)).status===422,'titular adulterado');bad=structuredClone(backup);bad.tabelas.usuarios=[];ok((await upload(g,bad)).status===422,'tabela extra');bad=structuredClone(backup);bad.tabelas.contas[0].sql='DELETE';ok((await upload(g,bad)).status===422,'coluna extra');
  p=await upload(a,backup);ok(p.status===200&&!!preview(p),'prévia');p=await a.req('/views/backup.php',{acao:'restaurar',token:preview(p),confirmar:'1',senha:'Teste-Conta-2026!',mcf_csrf:a.csrf});ok(p.status===422&&p.text.includes('conta vazia'),'não sobrescreve');
  bad=structuredClone(backup);bad.tabelas.cartoes[0].compra_id=999999;p=await upload(b,bad); // Conta beta não vazia também deve ser protegida.
  p=await upload(g,bad);const wrong=preview(p);p=await g.req('/views/backup.php',{acao:'restaurar',token:wrong,confirmar:'1',senha:'Teste-Conta-2026!',mcf_csrf:g.csrf});ok(p.status===422,'vínculo inválido');ok(db('SELECT COUNT(*) FROM compras WHERE usuario_id=3')==='0','rollback integral');
  // Cooldown de senha faz parte do formulário, não do processamento dos dados.
  await new Promise(r=>setTimeout(r,3100));p=await upload(g,backup);const good=preview(p);ok((await b.req('/views/backup.php',{acao:'restaurar',token:good,confirmar:'1',senha:'Teste-Conta-2026!',mcf_csrf:b.csrf})).status===422,'token entre sessões');
  p=await g.req('/views/backup.php',{acao:'restaurar',token:good,confirmar:'1',senha:'Teste-Conta-2026!',mcf_csrf:g.csrf});ok(p.status===200&&p.text.includes('Recuperação concluída'),'restauração');
  ok(db('SELECT COUNT(*) FROM cartoes c JOIN compras b ON c.compra_id=b.id AND c.usuario_id=b.usuario_id WHERE c.usuario_id=3')==='1','vínculo cartão');ok(db('SELECT COUNT(*) FROM operacoes o JOIN corretoras c ON o.corretora_id=c.id AND o.usuario_id=c.usuario_id WHERE o.usuario_id=3')==='1','vínculo corretora');
  ok(db("SELECT COUNT(*) FROM movimentacoes_financeiras m JOIN rendas r ON m.origem_id=r.id AND m.usuario_id=r.usuario_id JOIN contas_financeiras c ON m.conta_id=c.id AND m.usuario_id=c.usuario_id WHERE m.usuario_id=3")==='1','origem e conta remapeadas');
  p=await g.req('/views/backup.php',{acao:'baixar',mcf_csrf:g.csrf});const restored=JSON.parse(p.text);
  for(const t of Object.keys(backup.tabelas)){ok(restored.tabelas[t].length===backup.tabelas[t].length,'contagem '+t);}
  ok(restored.tabelas.investimentos_internacionais[0].valor_unitario===backup.tabelas.investimentos_internacionais[0].valor_unitario,'preço preservado');ok(db("SELECT nome FROM compras WHERE usuario_id=1")==='COMPRA_ALFA','origem preservada');ok(db("SELECT nome FROM contas WHERE usuario_id=2")==='BETA_PRIVADO','terceiro preservado');
  fs.writeFileSync(path.join(out,'http-result.json'),JSON.stringify({passed:n,database:'mcf_reports_test',port:3307},null,2));console.log('PASS: '+n+' verificações de backup e recuperação');
  if(process.argv.includes('--serve'))await new Promise(()=>{});
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>server?.kill());
