<?php
require_once __DIR__.'/../config.php';
if($_SERVER['REQUEST_METHOD']!=='GET') mcfFalhar(405,'O histórico é somente de consulta.');
$uid=mcfUsuarioId();$page=filter_var($_GET['pagina']??1,FILTER_VALIDATE_INT,['options'=>['min_range'=>1,'max_range'=>1000000]]);if(!$page)mcfFalhar(422,'Página inválida.');
$m=$_GET['modulo']??'';if(!is_string($m)||($m!==''&&!isset(mcfModulosCompartilhaveis()[$m])))mcfFalhar(422,'Módulo inválido.');
$offset=($page-1)*50;
$s=$conn->prepare("SELECT h.*,u.nome AS ator_nome,u.email AS ator_email FROM historico_alteracoes h LEFT JOIN usuarios u ON u.id=h.ator_id WHERE h.proprietario_id=? AND (?='' OR h.modulo=?) ORDER BY h.id DESC LIMIT 51 OFFSET ?");$s->bind_param('issi',$uid,$m,$m,$offset);$s->execute();$rows=$s->get_result()->fetch_all(MYSQLI_ASSOC);$s->close();$more=count($rows)>50;$rows=array_slice($rows,0,50);
$e=static fn($v)=>htmlspecialchars((string)($v??''),ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');
$labels=['valor'=>'Valor','valor_unitario'=>'Preço unitário','valor_investido'=>'Valor investido','saldo_inicial'=>'Saldo inicial','quantidade'=>'Quantidade','tipo_operacao'=>'Operação','nome'=>'Nome','descricao'=>'Descrição','ticker'=>'Ativo','tipo_ativo'=>'Tipo de ativo','paga'=>'Pago','recebido'=>'Recebido','ativa'=>'Ativa','data'=>'Data','vencimento'=>'Vencimento','datacom'=>'Data com','datapag'=>'Pagamento','preco'=>'Preço','titulo'=>'Título','texto'=>'Nota'];
$format=static function($key,$value) { if($value===null)return '—'; if(in_array($key,['paga','recebido','ativa'],true))return (int)$value===1?'Sim':'Não'; if(is_numeric($value)&&preg_match('/valor|saldo|preco|percentual|quantidade|lucro|taxas|darf|imposto|total_compra|total_venda/',$key))return rtrim(rtrim(number_format((float)$value,8,',','.'),'0'),',');return (string)$value; };
$cssPagina='/MyCashFlow/assets/css/compartilhamento.css';require __DIR__.'/../includes/header.php';require __DIR__.'/../includes/menu.php';
?>
<main class="compartilhamento"><h2>Histórico de alterações dos meus dados</h2><p>Registra alterações feitas a partir desta atualização. O histórico é visível somente ao titular e não pode ser editado por esta página.</p><form method="get"><label>Módulo <select name="modulo"><option value="">Todos</option><?php foreach(mcfModulosCompartilhaveis() as $key=>$label): ?><option value="<?= $e($labels[$key]??ucfirst(str_replace('_',' ',$key))) ?>"<?= $m===$key?' selected':'' ?>><?= $e($label) ?></option><?php endforeach; ?></select></label><button>Filtrar</button></form>
<?php if(!$rows): ?><p>Nenhuma alteração registrada neste filtro.</p><?php endif; ?>
<?php foreach($rows as $r): $before=json_decode($r['antes']??'null',true)??[];$after=json_decode($r['depois']??'null',true)??[]; ?><section><h3><?= $e(['cadastrar'=>'Cadastro','editar'=>'Edição','excluir'=>'Exclusão'][$r['acao']]) ?> · <?= $e(mcfModulosCompartilhaveis()[$r['modulo']]??$r['modulo']) ?></h3><p><?= $e(date('d/m/Y H:i:s',strtotime($r['criado_em']))) ?> · Por <?= $e($r['ator_nome']?:($r['ator_email']?:'Usuário #'.$r['ator_id'])) ?> · Registro: <?= $e($after['nome']??$before['nome']??$after['ticker']??$before['ticker']??('#'.$r['registro'])) ?></p><details><summary>Ver valores anteriores e novos</summary><div class="tabela-scroll"><table><thead><tr><th>Campo</th><th>Antes</th><th>Depois</th></tr></thead><tbody><?php foreach(array_unique(array_merge(array_keys($before),array_keys($after))) as $key): if(in_array($key,['id','usuario_id','criado_em','atualizado_em','logo','versao','chave_descricao','identificador_ofx','fitid'],true))continue; if($r['acao']==='editar'&&($before[$key]??null)===($after[$key]??null))continue; ?><tr><td><?= $e($key) ?></td><td><?= $e($format($key,$before[$key]??null)) ?></td><td><?= $e($format($key,$after[$key]??null)) ?></td></tr><?php endforeach; ?></tbody></table></div></details></section><?php endforeach; ?>
<p><?php if($page>1): ?><a href="?<?= $e(http_build_query(['modulo'=>$m,'pagina'=>$page-1])) ?>">Anterior</a><?php endif; ?> <?php if($more): ?><a href="?<?= $e(http_build_query(['modulo'=>$m,'pagina'=>$page+1])) ?>">Próxima</a><?php endif; ?></p></main><?php require __DIR__.'/../includes/footer.php'; ?>
