const assert=require('assert/strict'),cp=require('child_process'),fs=require('fs'),path=require('path');
const {Client,base}=require('./client.cjs');
const db=s=>cp.execFileSync('C:/xampp/mysql/bin/mysql.exe',['-u','root','-N','-B','mcf_test_20260921'],{input:s,encoding:'utf8'}).trim();
const tables=db('SHOW TABLES').split(/\r?\n/).filter(t=>!t.startsWith('compartilhamento'));
const snap=()=>Object.fromEntries(tables.map(t=>[t,db('SELECT * FROM `'+t+'`')]));
let n=0;const ok=(v,m)=>{assert.ok(v,m);n++;};
const url='/views/compartilhamento.php';
const post=(c,data)=>c.req(url,{mcf_csrf:c.csrf,...data});
const state=id=>{const [estado,versao]=db('SELECT estado,versao FROM compartilhamentos WHERE id='+id).split('\t');return {estado,versao};};
const action=(c,id,acao,extra={})=>post(c,{id,acao,versao:state(id).versao,...extra});
const view=(c,id,modulo,extra='')=>c.req('/views/compartilhado.php?id='+id+'&modulo='+modulo+'&inicio=2026-01-01&fim=2026-12-31'+extra);
(async()=>{
 const before=snap();
 const a=new Client(),b=new Client(),third=new Client(),anon=new Client();
 await a.login('alfa@example.test');await b.login('beta@example.test');
 await third.req('/views/login/login.php');await third.req('/views/login/login.php',{email:'cadastro@example.test',senha:'Cadastro-Teste-2026!',mcf_csrf:third.csrf});
 for(const c of [a,b,third])ok((await c.req(url)).status===200,'gestão própria disponível');
 ok((await anon.req(url)).status===401,'gestão exige login');
 ok((await anon.req(url,{acao:'convidar'})).status===401,'POST exige login');
 ok((await view(anon,1,'despesas')).status===401,'consulta exige login');
 ok((await a.req(url,{acao:'convidar',email:'beta@example.test','modulos[]':'despesas'})).status===403,'convite exige CSRF');
 ok((await post(a,{acao:'convidar',email:'beta@example.test','modulos[]':'despesas',mcf_csrf:b.csrf})).status===403,'CSRF de outra conta rejeitado');
 for(const data of [{email:'alfa@example.test','modulos[]':'despesas'},{email:'ausente@example.test','modulos[]':'despesas'},{email:'beta@example.test'},{email:'beta@example.test','modulos[]':'usuarios'},{'email[]':'beta@example.test','modulos[]':'despesas'}])ok((await post(a,{acao:'convidar',...data})).status===422,'convite inválido');
 ok(db('SELECT COUNT(*) FROM compartilhamentos')==='0','convites inválidos sem persistência');
 ok((await post(a,{acao:'convidar',email:' BETA@EXAMPLE.TEST ','modulos[]':'despesas',proprietario_id:2,leitor_id:3,estado:'ativo',admin:1})).status===303,'convite por email normalizado');
 const id=Number(db('SELECT id FROM compartilhamentos WHERE proprietario_id=1 AND leitor_id=2'));
 ok(id>0&&state(id).estado==='pendente','identidades e estado fixados no servidor');
 ok((await view(b,id,'despesas')).status===404,'pendente não permite consulta');
 ok((await view(third,id,'despesas')).status===404,'terceiro sem acesso');
 ok((await action(a,id,'aceitar')).status===422,'remetente não aceita pelo leitor');
 ok((await action(third,id,'aceitar')).status===422,'terceiro não aceita convite');
 ok((await post(a,{acao:'convidar',email:'beta@example.test','modulos[]':'receitas'})).status===422,'convite duplicado não altera permissão');
 const stale=state(id).versao;
 ok((await action(a,id,'revisar',{'modulos[]':'despesas'})).status===303,'titular revisa convite');
 ok((await action(b,id,'aceitar',{versao:stale})).status===422,'aceitação desatualizada rejeitada');
 ok((await action(b,id,'aceitar')).status===303,'destinatário aceita');
 ok((await action(b,id,'aceitar')).status===422,'aceitação repetida rejeitada');
 let r=await view(b,id,'despesas');ok(r.status===200&&r.text.includes('ALFA_PRIVADO')&&!r.text.includes('BETA_PRIVADO'),'leitor consulta somente titular autorizado');
 ok(r.text.includes('Somente leitura')&&r.text.includes('alfa@example.test')&&r.text.includes('R$ 112,00'),'identificação e total corretos');
 ok(r.text.includes('beta@example.test'),'cabeçalho mantém ator conectado');
 ok((await view(b,id,'receitas')).status===404,'módulo não autorizado bloqueado');
 ok((await view(b,id,'despesas','&secao=operacoes_nacionais')).status===404,'seção de outro módulo bloqueada');
 ok((await view(b,id,'despesas','&proprietario_id=3&usuario_id=3')).text.includes('ALFA_PRIVADO'),'IDs adicionais não mudam proprietário');
 ok((await a.req('/views/compartilhado.php?id='+id+'&modulo=despesas')).status===404,'concessão não cria acesso reverso');
 ok((await b.req('/views/compartilhado.php?id='+id+'&modulo=despesas',{mcf_csrf:b.csrf,acao:'excluir',id:101})).status===405,'consulta bloqueia escrita mesmo com CSRF');
 ok((await action(b,id,'revisar',{'modulos[]':'receitas'})).status===422,'leitor não aumenta permissões');
 ok((await action(b,id,'revogar')).status===422,'leitor não executa ação de titular');
 ok((await action(third,id,'revogar')).status===422,'terceiro não revoga');
 const regular=await b.req('/views/contas.php?usuario_id=1');ok(regular.text.includes('BETA_PRIVADO')&&!regular.text.includes('ALFA_PRIVADO'),'área normal continua privada após consulta');
 // Tentativa de alterar registro autorizado apenas para leitura por endpoint legado.
 await b.req('/views/contas.php');
 await b.req('/views/contas.php',{mcf_csrf:b.csrf,deletar_conta:1,id:101,alcance:'somente',usuario_id:1});
 ok(db('SELECT nome FROM contas WHERE id=101')==='ALFA_PRIVADO','não edita titular via endpoint legado');
 ok((await action(a,id,'revogar')).status===303,'titular revoga');
 ok((await view(b,id,'despesas')).status===404,'URL antiga negada após revogação');
 ok((await action(b,id,'aceitar')).status===422,'não reativa revogado');
 const modules=['despesas','receitas','cartao','saldos','investimentos','daytrade','analise'];
 const moduleFields=Object.fromEntries(modules.map((m,i)=>['modulos['+i+']',m]));
 ok((await action(a,id,'revisar',moduleFields)).status===303,'novo convite com todos os módulos');
 ok((await view(b,id,'despesas')).status===404,'reenvio aguarda aceitação');
 ok((await action(b,id,'aceitar')).status===303,'aceita novos módulos');
 const sections={despesas:['despesas'],receitas:['receitas'],cartao:['parcelas'],saldos:['contas','movimentacoes'],investimentos:['posicoes_nacionais','posicoes_internacionais','operacoes_nacionais','operacoes_internacionais','proventos'],daytrade:['operacoes'],analise:['marcacoes','acompanhamento']};
 for(const [module,ss] of Object.entries(sections))for(const section of ss){
   r=await view(b,id,module,'&secao='+section);
   ok(r.status===200,'consulta autorizada '+module+'/'+section);
   ok(!r.text.includes('BETA_PRIVADO')&&!r.text.includes('password_hash')&&!r.text.includes('auth_version'),'sem vazamento '+section);
   ok((await view(third,id,module,'&secao='+section)).status===404,'terceiro bloqueado '+section);
 }
 r=await view(b,id,'investimentos','&secao=posicoes_internacionais');ok(r.text.includes('US$ 601,0000'),'custo internacional correto');
 r=await view(b,id,'saldos','&secao=contas');ok(r.text.includes('ALFA_PRIVADO'),'saldo próprio do titular');
 ok((await view(b,id,'despesas','&inicio=2026-02-31')).status===422,'data inválida');
 ok((await view(b,id,'despesas','&inicio=2027-01-01&fim=2026-01-01')).status===422,'intervalo invertido');
 ok((await view(b,id,'despesas','&pagina=-1')).status===422,'paginação inválida');
 ok((await view(b,id,'despesas','&pagina=2')).status===200,'paginação funciona');
 ok((await b.req('/views/compartilhado.php?id[]=1&modulo=despesas')).status===422,'ID malformado');
 ok((await b.req('/views/compartilhado.php?id='+id+'&modulo[]=despesas')).status===422,'módulo malformado');
 ok((await b.req('/views/compartilhado.php?id='+id+'&modulo=usuarios')).status===404,'módulo interno não existe');
 db("UPDATE usuarios SET status_assinatura='inativo' WHERE id=1");ok((await view(b,id,'despesas')).status===404,'titular inativo bloqueia consulta');db("UPDATE usuarios SET status_assinatura='ativo' WHERE id=1");
 ok((await action(b,id,'sair')).status===303,'leitor encerra seu acesso');
 ok((await view(b,id,'despesas')).status===404,'saída invalida consulta');
 ok((await action(a,id,'revisar',{'modulos[]':'receitas'})).status===303,'convite restrito');
 ok((await action(b,id,'recusar')).status===303,'recusa');
 ok((await view(b,id,'receitas')).status===404,'recusado não consulta');
 ok((await action(a,id,'revisar',{'modulos[]':'receitas'})).status===303,'reenviar após recusa');
 ok((await action(b,id,'aceitar')).status===303,'aceitar após recusa');
 ok((await view(b,id,'despesas')).status===404,'módulo retirado permanece bloqueado');
 ok((await view(b,id,'receitas')).status===200,'somente novo módulo');
 // Um leitor pode compartilhar apenas os próprios dados, nunca repassar a concessão recebida.
 ok((await post(b,{acao:'convidar',email:'cadastro@example.test','modulos[]':'despesas',proprietario_id:1})).status===303,'leitor só convida em nome próprio');
 const onward=Number(db('SELECT id FROM compartilhamentos WHERE proprietario_id=2 AND leitor_id=(SELECT id FROM usuarios WHERE email_normalizado=\'cadastro@example.test\')'));
 ok(onward>0,'proprietário não é herdado do compartilhamento aberto');
 ok((await action(third,onward,'aceitar')).status===303,'terceiro aceita somente convite recebido');
 r=await view(third,onward,'despesas');ok(r.status===200&&r.text.includes('BETA_PRIVADO')&&!r.text.includes('ALFA_PRIVADO'),'consulta não é transitiva');
 ok((await view(third,id,'receitas')).status===404,'terceiro não herda acesso ao primeiro titular');
 ok((await action(b,onward,'revogar')).status===303,'revoga convite secundário');
 // Alterar os dados de identificação não transfere nem perde a permissão.
 await a.req('/views/perfil.php');
 ok((await a.req('/views/perfil.php',{mcf_csrf:a.csrf,acao:'dados',nome:'Titular & Teste',email:'titular-compartilhamento@example.test',senha_atual:'Teste-Conta-2026!'})).status===303,'titular atualiza identificação');
 r=await view(b,id,'receitas');ok(r.status===200&&r.text.includes('Titular &amp; Teste')&&r.text.includes('ALFA_PRIVADO'),'vínculo estável e identificação escapada');
 db("UPDATE usuarios SET nome=NULL,email='alfa@example.test' WHERE id=1");
 // Texto persistido é sempre exibido como texto, inclusive em notas compartilhadas.
 db("UPDATE analise_marcacoes SET titulo='<img src=x onerror=alert(1)>' WHERE id=101");
 await action(a,id,'revisar',{'modulos[]':'analise'});await action(b,id,'aceitar');
 r=await view(b,id,'analise');ok(r.status===200&&!r.text.includes('<img src=x')&&r.text.includes('&lt;img src=x'),'XSS em marcação escapado');
 db("UPDATE analise_marcacoes SET titulo='ALFA_PRIVADO' WHERE id=101");
 // updated_at é restaurado exclusivamente nesta fixture para a comparação integral.
 const annotationBefore=before.analise_marcacoes.split(/\r?\n/).find(row=>row.startsWith('101\t')).split('\t');
 db("UPDATE analise_marcacoes SET atualizado_em='"+annotationBefore.at(-1)+"' WHERE id=101");
 await action(a,id,'revisar',{'modulos[]':'receitas'});await action(b,id,'aceitar');
 const replay=await fetch(base+url,{method:'PUT',headers:{cookie:a.cookie}});ok(replay.status===405,'PUT rejeitado');
 const after=snap();for(const t of tables)ok(after[t]===before[t],'registros preservados: '+t);
 ok(!(await third.req(url)).text.includes('alfa@example.test'),'terceiro não lista convites alheios');
 ok((await a.req(url+'?acao=revogar&id='+id)).status===200&&state(id).estado==='ativo','GET não revoga');
 console.log('PASS: '+n+' verificações de compartilhamento, consentimento, revogação e isolamento');
 fs.writeFileSync(path.join(process.env.MCF_TEST_OUTPUT,'compartilhamento-result.json'),JSON.stringify({passed:n},null,2));
})().catch(e=>{console.error('FAIL compartilhamento: '+e.message);process.exitCode=1;});
