const assert=require('assert/strict'),cp=require('child_process'),fs=require('fs'),path=require('path');
const {Client,base}=require('./client.cjs');
const db=s=>cp.execFileSync('C:/xampp/mysql/bin/mysql.exe',['-u','root','-N','-B','mcf_test_20260921'],{input:s,encoding:'utf8'}).trim();
let n=0;const ok=(v,m)=>{assert.ok(v,m);n++;};
const token=(h,k)=>h.match(new RegExp('name="'+k+'"\\s+value="([a-f0-9]+)"'))?.[1]||'';
const id=Number(db('SELECT id FROM compartilhamentos WHERE proprietario_id=1 AND leitor_id=2'));
const version=()=>db('SELECT versao FROM compartilhamentos WHERE id='+id);
const modules=['despesas','receitas','cartao','saldos','investimentos','daytrade','analise'];
const routes=['contas.php','rendas.php','cartao.php','saldos.php','investimentos_nacionais.php','investimentos_internacionais.php','div_datacom.php','daytrade.php','analise.php'];
const fields=(ms,nivel)=>Object.fromEntries(ms.flatMap((m,i)=>[['modulos['+i+']',m],['nivel['+m+']',nivel]]));
const page=(c,p)=>c.req('/views/'+p+(p.includes('?')?'&':'?')+'compartilhamento='+id);
const post=(c,p,d={})=>c.req('/views/'+p+(p.includes('?')?'&':'?')+'compartilhamento='+id,{mcf_csrf:c.csrf,mcf_contexto:id,mcf_contexto_versao:version(),...d});
(async()=>{
 const a=new Client(),b=new Client(),stranger=new Client();await a.login('alfa@example.test');await b.login('beta@example.test');
 await stranger.req('/views/login/login.php');await stranger.req('/views/login/login.php',{email:'cadastro@example.test',senha:'Cadastro-Teste-2026!',mcf_csrf:stranger.csrf});
 const privateTables=['contas','rendas','compras','cartoes','corretoras','corretora_taxas','operacoes','contas_financeiras','movimentacoes_financeiras','investimentos_nacionais','investimentos_internacionais','analise_marcacoes','analise_acompanhamento'];
 const originalB=Object.fromEntries(privateTables.map(t=>[t,db('SELECT * FROM '+t+' WHERE usuario_id=2')]));
 async function grant(ms,nivel) {
   await a.req('/views/compartilhamento.php');
   let r=await a.req('/views/compartilhamento.php',{mcf_csrf:a.csrf,acao:'revisar',id,versao:version(),...fields(ms,nivel)});ok(r.status===303,'salvar níveis');
   await b.req('/views/compartilhamento.php');r=await b.req('/views/compartilhamento.php',{mcf_csrf:b.csrf,acao:'aceitar',id,versao:version()});ok(r.status===303,'aceitar níveis');
 }
 await grant(modules,'leitura');
 for(const p of routes){ok((await page(b,p)).status===403,'leitor não abre edição '+p);ok((await post(b,p)).status===403,'leitor não escreve '+p);}
 await grant(modules,'edicao');
 for(const p of routes){let r=await page(b,p);ok(r.status===200,'editor abre '+p);ok(r.text.includes('Gerenciando dados de')&&r.text.includes('alfa@example.test'),'titular visível '+p);ok((await page(stranger,p)).status===404,'terceiro negado '+p);}
 let r=await page(b,'contas.php');
 ok(r.text.includes('name="mcf_contexto" value="'+id+'"'),'formulários carregam dono autorizado');
 ok(r.text.includes('data-mcf-own href="/MyCashFlow/views/dashboard.php"'),'saída para própria conta');
 ok((await b.req('/views/contas.php',{mcf_csrf:b.csrf,mcf_contexto:id,mcf_contexto_versao:version(),nova_conta:1})).status===403,'contexto perdido não grava na conta errada');
 ok((await b.req('/views/contas.php?compartilhamento='+id,{mcf_csrf:b.csrf,nova_conta:1})).status===403,'formulário sem vínculo não grava');
 ok((await page(b,'perfil.php')).status===403,'delegação não alcança perfil');
 ok((await page(b,'configuracao.php')).status===403,'delegação não alcança configuração');
 r=await post(b,'contas.php',{nova_conta:1,nomeConta:'DELEGADA',tipoConta:'unica',categoria:'pessoal',vencimento:'2026-09-20',valor:33,usuario_id:2});ok(r.status===302,'cria despesa delegada');
 ok(r.location.includes('compartilhamento='+id),'redirecionamento preserva titular');
 const conta=db("SELECT id FROM contas WHERE nome='DELEGADA' AND usuario_id=1");ok(!!conta,'despesa pertence ao titular');
 await post(b,'contas.php',{ajustar_valor:1,id:conta,novo_valor:44,alcance:'somente'});ok(db('SELECT valor FROM contas WHERE id='+conta)==='44.00','edita despesa delegada');
 await post(b,'contas.php',{deletar_conta:1,id:conta,alcance:'somente'});ok(db('SELECT COUNT(*) FROM contas WHERE id='+conta)==='0','exclui despesa delegada');
 await post(b,'rendas.php',{nova_renda:1,nome:'DELEGADA',descricao:'gestão',tipoRenda:'unica',classificacao:'extra',data:'2026-09-20',valor:22,usuario_id:2});
 const renda=db("SELECT id FROM rendas WHERE nome='DELEGADA' AND usuario_id=1");ok(!!renda,'receita do titular');
 await post(b,'rendas.php',{deletar_renda:1,id:renda,alcance:'somente'});ok(db('SELECT COUNT(*) FROM rendas WHERE id='+renda)==='0','exclui receita do titular');
 r=await page(b,'cartao.php');const csrfCard=token(r.text,'csrf_cartao');
 await post(b,'cartao.php',{csrf_cartao:csrfCard,renomear_compra:1,compra_id:101,novo_nome:'CARTAO_DELEGADO',repetir_nome:0});ok(db('SELECT nome FROM compras WHERE id=101')==='CARTAO_DELEGADO','edita compra do titular');
 await post(b,'cartao.php',{csrf_cartao:csrfCard,renomear_compra:1,compra_id:101,novo_nome:'ALFA_PRIVADO',repetir_nome:0});
 r=await page(b,'saldos.php');let csrf=token(r.text,'csrf');
 await post(b,'saldos.php',{csrf,acao:'nova_conta',nome:'CONTA_DELEGADA',tipo:'carteira',instituicao:'Teste',saldo_inicial:0,data_saldo_inicial:'2026-01-01',usuario_id:2});
 const account=db("SELECT id FROM contas_financeiras WHERE nome='CONTA_DELEGADA' AND usuario_id=1");ok(!!account,'saldo pertence ao titular');
 await post(b,'saldos.php',{csrf,acao:'nova_movimentacao',conta_id:account,tipo_movimentacao:'entrada',data:'2026-09-20',descricao:'MOV_DELEGADO',valor:55,usuario_id:2});ok(db("SELECT COUNT(*) FROM movimentacoes_financeiras WHERE descricao='MOV_DELEGADO' AND usuario_id=1")==='1','movimento pertence ao titular');
 await post(b,'daytrade/salvar_corretora.php',{corretora:'DELEGADA',nome_taxa:'Teste',taxa_valor:'0.01',usuario_id:2});
 const broker=db("SELECT id FROM corretoras WHERE nome='DELEGADA' AND usuario_id=1");ok(!!broker,'corretora do titular');
 await post(b,'daytrade/salvar_operacao.php',{corretora_id:broker,data:'2026-09-20',acao:'TEST3',quantidade:1,valor_compra:10,valor_venda:11,usuario_id:2});ok(db('SELECT COUNT(*) FROM operacoes WHERE corretora_id='+broker+' AND usuario_id=1')==='1','day trade do titular');
 ok((await post(b,'daytrade/salvar_operacao.php',{corretora_id:201,data:'2026-09-20',acao:'TEST3',quantidade:1,valor_compra:10,valor_venda:11})).status===404,'não cria vínculo com conta do leitor');
 for(const [p,ticker,tipo] of [['investimentos_nacionais.php','TEST3','acao'],['investimentos_internacionais.php','TEST','stock']]) {
   r=await page(b,p);csrf=token(r.text,'csrf');
   r=await post(b,p,{csrf,tipo_ativo:tipo,ticker,modo:'quantidade',quantidade:'2',valor_operacao:'20',valor_unitario:'10.00',data:'2026-09-20',acao:'compra',usuario_id:2});ok(r.status===302,'registro delegado '+p);
 }
 ok(db("SELECT COUNT(*) FROM investimentos_nacionais WHERE ticker='TEST3' AND usuario_id=1")==='1','ação do titular');
 ok(db("SELECT COUNT(*) FROM investimentos_internacionais WHERE ticker='TEST' AND usuario_id=1")==='1','ativo internacional do titular');
 const opid=db("SELECT id FROM investimentos_nacionais WHERE ticker='TEST3' AND usuario_id=1");
 r=await page(b,'investimentos_operacoes.php');let form=Array.from(r.text.matchAll(/<form\b[^>]*>[\s\S]*?<\/form>/g)).map(m=>m[0]).find(f=>f.includes('name="operacao_id" value="'+opid+'"'));
 let revisao=token(form||'','revisao');ok(!!revisao,'formulário de correção');
 r=await post(b,'investimentos_operacoes.php',{mercado:'nacional',acao:'corrigir',operacao_id:opid,revisao,ticker:'TEST3',tipo_ativo:'acao',tipo_operacao:'compra',quantidade:'3',valor_unitario:'11.00',data:'2026-09-20'});ok(r.status===303,'correção delegada');
 ok(db('SELECT quantidade FROM investimentos_nacionais WHERE id='+opid)==='3','quantidade corrigida');
 ok((await post(b,'investimentos_operacoes.php',{mercado:'nacional',acao:'excluir',operacao_id:opid,revisao})).status===422,'revisão antiga não exclui');
 ok((await post(b,'investimentos_operacoes.php',{mercado:'nacional',acao:'excluir',operacao_id:201,revisao})).status===422,'ID do leitor não é corrigido no titular');
 const getRevision=async(op,mercado='nacional')=>{const html=(await page(b,'investimentos_operacoes.php?mercado='+mercado)).text;const f=Array.from(html.matchAll(/<form\b[^>]*>[\s\S]*?<\/form>/g)).map(m=>m[0]).find(v=>v.includes('name="operacao_id" value="'+op+'"'));return token(f||'','revisao');};
 r=await page(b,'investimentos_nacionais.php');csrf=token(r.text,'csrf');
 await post(b,'investimentos_nacionais.php',{csrf,tipo_ativo:'acao',ticker:'TEST3',quantidade:'2',valor_unitario:'12.00',data:'2026-09-21',acao:'venda'});
 revisao=await getRevision(opid);
 ok((await post(b,'investimentos_operacoes.php',{mercado:'nacional',acao:'corrigir',operacao_id:opid,revisao,ticker:'TEST3',tipo_ativo:'acao',tipo_operacao:'compra',quantidade:'1',valor_unitario:'11.00',data:'2026-09-20'})).status===422,'correção não permite venda sem posição');
 ok(db('SELECT quantidade FROM investimentos_nacionais WHERE id='+opid)==='3','correção inválida não altera parcialmente');
 ok((await post(b,'investimentos_operacoes.php',{mercado:'nacional',acao:'excluir',operacao_id:opid,revisao})).status===422,'exclusão não deixa venda sem posição');
 const sale=db("SELECT id FROM investimentos_nacionais WHERE ticker='TEST3' AND usuario_id=1 AND tipo_operacao='venda'");
 ok((await post(b,'investimentos_operacoes.php',{mercado:'nacional',acao:'excluir',operacao_id:sale,revisao:await getRevision(sale)})).status===303,'exclusão válida de venda');
 const intl=db("SELECT id FROM investimentos_internacionais WHERE ticker='TEST' AND usuario_id=1");
 ok((await post(b,'investimentos_operacoes.php?mercado=internacional',{mercado:'internacional',acao:'corrigir',operacao_id:intl,revisao:await getRevision(intl,'internacional'),ticker:'TEST',tipo_ativo:'stock',tipo_operacao:'compra',quantidade:'0.125',valor_unitario:'80.0000',data:'2026-09-20'})).status===303,'correção internacional fracionária');
 ok(db('SELECT valor_investido FROM investimentos_internacionais WHERE id='+intl)==='10.00000000','valor internacional recalculado');
 r=await page(b,'analise.php');const csrfAnalise=r.text.match(/data-csrf="([a-f0-9]+)"/)[1];ok(r.text.includes('data-user="2:dono:1"'),'preferências separadas por ator e titular');
 const api=async(data)=>{const resp=await fetch(base+'/views/analise/api.php?compartilhamento='+id,{method:'POST',headers:{cookie:b.cookie,'Content-Type':'application/json','X-CSRF-Token':csrfAnalise,'X-MCF-Context-Version':version()},body:JSON.stringify(data)});return {status:resp.status,text:await resp.text()};};
 r=await api({action:'save',id:0,versao:0,ticker:'PETR4',tipo_ativo:'acao',tipo:'nota',titulo:'NOTA_DELEGADA',texto:'Teste',preco:null,cor:'#ff0000',usuario_id:2});ok(r.status===200,'nota delegada');
 ok(db("SELECT COUNT(*) FROM analise_marcacoes WHERE titulo='NOTA_DELEGADA' AND usuario_id=1")==='1','nota permanece no titular');
 const lost=await fetch(base+'/views/analise/api.php',{method:'POST',headers:{cookie:b.cookie,'Content-Type':'application/json','X-CSRF-Token':csrfAnalise,'X-MCF-Context-Version':version()},body:JSON.stringify({action:'watch',ticker:'TEST3',tipo_ativo:'acao'})});ok(lost.status===403,'API com contexto perdido não escreve na própria conta');
 const shared=await b.req('/views/visao_conjunta.php?modulo=receitas');ok(shared.status===200&&shared.text.includes('ALFA_PRIVADO')&&shared.text.includes('BETA_PRIVADO')&&shared.text.includes('R$ 3.334,00'),'total de receitas autorizado');
 ok((await b.req('/views/visao_conjunta.php?modulo=receitas&pessoas[]=1')).text.includes('R$ 1.112,00'),'seleciona só titular');
 ok((await b.req('/views/visao_conjunta.php?modulo=receitas&pessoas[]=1&pessoas[]=1')).text.includes('R$ 1.112,00'),'não duplica titular');
 ok((await stranger.req('/views/visao_conjunta.php?modulo=investimentos&pessoas[]=1')).status===403,'consolidação não contorna autorização');
 ok((await b.req('/views/visao_conjunta.php?modulo=receitas&selecionar=1')).status===422,'nenhuma pessoa selecionada não soma todos');
 r=await b.req('/views/visao_conjunta.php?modulo=investimentos');ok(r.status===200&&r.text.includes('Posições por titular')&&r.text.includes('Lucro/prejuízo'),'visão conjunta de investimentos');
 const oldVersion=version();await grant(['analise'],'edicao');
 ok((await page(b,'investimentos_nacionais.php')).status===404,'módulo removido bloqueado');
 ok((await post(b,'analise/api.php')).status===403,'API mantém CSRF próprio');
 r=await b.req('/views/analise/api.php?compartilhamento='+id+'&action=state&ticker=PETR4&tipo_ativo=acao');const state=JSON.parse(r.text);ok(r.status===200&&state.operations.length===0&&state.position.preco_medio===null,'análise não expõe investimentos sem autorização');
 ok(state.annotations.some(x=>x.titulo==='NOTA_DELEGADA'),'notas continuam autorizadas');
 ok((await b.req('/views/visao_conjunta.php?modulo=investimentos&pessoas[]=1')).status===403,'consolidação bloqueia módulo removido');
 await grant(modules,'edicao');
 ok((await post(b,'contas.php',{mcf_contexto_versao:oldVersion})).status===403,'formulário antes de nova permissão é recusado');
 for(const t of privateTables)ok(db('SELECT * FROM '+t+' WHERE usuario_id=2')===originalB[t],'dados do leitor preservados: '+t);
 await b.req('/views/configuracao.php');ok((await b.req('/views/configuracao.php')).text.includes('beta@example.test'),'identidade original preservada');
 await a.req('/views/compartilhamento.php');await a.req('/views/compartilhamento.php',{mcf_csrf:a.csrf,id,versao:version(),acao:'revogar'});
 for(const p of routes)ok((await post(b,p)).status===404,'revogação bloqueia POST '+p);
 console.log('PASS: '+n+' verificações de edição delegada e visão conjunta');fs.writeFileSync(path.join(process.env.MCF_TEST_OUTPUT,'compartilhamento-edicao-result.json'),JSON.stringify({passed:n},null,2));
})().catch(e=>{console.error('FAIL edição: '+e.message);process.exitCode=1;});
