const path=require('path');
const assert=require('assert/strict'),fs=require('fs'),cp=require('child_process');const {Client,base}=require('./client.cjs');
const db=sql=>cp.execFileSync('C:/xampp/mysql/bin/mysql.exe',['-u','root','--batch','--skip-column-names','mcf_test_20260921'],{input:sql,encoding:'utf8',stdio:['pipe','pipe','pipe']}).trim();
const tables=['contas','rendas','compras','cartoes','corretoras','corretora_taxas','operacoes','ofx_importacoes','cartao_nomes_recorrentes','contas_financeiras','movimentacoes_financeiras','investimentos_nacionais','investimentos_internacionais','div_datacom','analise_acompanhamento','analise_marcacoes'];
let n=0;const ok=(v,label)=>{assert.ok(v,label);n++;};
const token=(h,k)=>h.match(new RegExp('name="'+k+'"\\s+value="([a-f0-9]+)"'))?.[1]||'';
async function prepare(c,p){const r=await c.req('/views/'+p);ok(r.status===200,'abrir '+p);return r.text;}
async function post(c,p,d){return c.req('/views/'+p,{mcf_csrf:c.csrf,...d});}
(async()=>{
const a=new Client(),b=new Client();await a.login('alfa@example.test');await b.login('beta@example.test');
for(const [c,uid,own] of [[a,1,101],[b,2,201]]){
 await prepare(c,'daytrade.php');let r=await post(c,'daytrade/salvar_corretora.php',{corretora:'MESMO_NOME',nome_taxa:'Taxa teste',taxa_valor:'0.01',usuario_id:999});ok(r.status===302,'nova corretora '+uid);
 const id=db(`SELECT id FROM corretoras WHERE nome='MESMO_NOME' AND usuario_id=${uid}`);ok(!!id,'corretora mesma descrição isolada');
 await post(c,'daytrade/editar_corretora.php',{corretora_id:id,acao:'adicionar_taxa',nome_taxa:'ADICIONAL',percentual:'0.02'});const ti=db(`SELECT id FROM corretora_taxas WHERE corretora_id=${id} AND nome_taxa='ADICIONAL' AND usuario_id=${uid}`);ok(!!ti,'adicionar taxa própria');
 await post(c,'daytrade/editar_corretora.php',{corretora_id:id,acao:'editar_taxa',taxa_id:ti,nome_taxa:'EDITADA',percentual:'0.03'});ok(db(`SELECT nome_taxa FROM corretora_taxas WHERE id=${ti}`)==='EDITADA','editar taxa própria');
 await post(c,'daytrade/editar_corretora.php',{corretora_id:id,acao:'excluir_taxa',taxa_id:ti});ok(db(`SELECT COUNT(*) FROM corretora_taxas WHERE id=${ti}`)==='0','excluir taxa própria');
 await post(c,'daytrade/salvar_operacao.php',{corretora_id:id,data:'2026-09-21',acao:'PETR4',quantidade:1,valor_compra:10,valor_venda:20,usuario_id:999});const op=db(`SELECT id FROM operacoes WHERE corretora_id=${id} AND usuario_id=${uid}`);ok(!!op,'nova operação própria');
 await post(c,'daytrade/ajustar_operacao.php',{id:op,corretora_id:id,total_compra:11,total_venda:21,taxas:1});ok(db(`SELECT total_compra FROM operacoes WHERE id=${op}`)==='11.00','ajustar própria');
 let html=await prepare(c,'saldos.php'),csrf=token(html,'csrf');
 await post(c,'saldos.php',{csrf,acao:'nova_conta',nome:'NOVO_SALDO',tipo:'carteira',instituicao:'Teste',saldo_inicial:0,data_saldo_inicial:'2026-01-01',usuario_id:999});const ci=db(`SELECT id FROM contas_financeiras WHERE usuario_id=${uid} AND nome='NOVO_SALDO'`);ok(!!ci,'nova conta financeira');
 await post(c,'saldos.php',{csrf,acao:'nova_movimentacao',conta_id:ci,tipo_movimentacao:'entrada',data:'2026-09-21',descricao:'NOVO_MOV',valor:70,usuario_id:999});const mi=db(`SELECT id FROM movimentacoes_financeiras WHERE conta_id=${ci} AND usuario_id=${uid}`);ok(!!mi,'novo movimento');
 await post(c,'saldos.php',{csrf,acao:'editar_movimentacao',movimentacao_id:mi,tipo_movimentacao:'entrada',data:'2026-09-21',descricao:'EDIT_MOV',valor:80});ok(db(`SELECT valor FROM movimentacoes_financeiras WHERE id=${mi}`)==='80.00','editar movimento');
 await post(c,'saldos.php',{csrf,acao:'transferir',conta_origem:own,conta_destino:ci,data:'2026-09-21',descricao:'TRANSFER_TEST',valor:10});ok(db(`SELECT COUNT(*) FROM movimentacoes_financeiras WHERE usuario_id=${uid} AND descricao LIKE 'TRANSFER_TEST%'`)==='2','transferência entre próprias');
 await post(c,'saldos.php',{csrf,acao:'excluir_movimentacao',movimentacao_id:mi});ok(db(`SELECT COUNT(*) FROM movimentacoes_financeiras WHERE id=${mi}`)==='0','excluir movimento próprio');
 await prepare(c,'div_datacom.php');await post(c,'div_datacom.php',{nova_div:1,ticker:'VALE3',tipo_ativo:'acao',datacom:'2026-09-21',datapag:'2026-09-21',valor:'1.25',tipo:'DIV',usuario_id:999});const di=db(`SELECT id FROM div_datacom WHERE ticker='VALE3' AND usuario_id=${uid}`);ok(!!di,'criar provento próprio');await post(c,'div_datacom.php',{ajustar_valor:1,id:di,novo_valor:2});ok(db(`SELECT valor FROM div_datacom WHERE id=${di}`)==='2.00000000','editar provento');await post(c,'div_datacom.php',{deletar_div:1,id:di});ok(db(`SELECT COUNT(*) FROM div_datacom WHERE id=${di}`)==='0','excluir provento');
 html=await prepare(c,'investimentos_nacionais.php');await post(c,'investimentos_nacionais.php',{csrf:token(html,'csrf'),tipo_ativo:'acao',ticker:'PETR4',quantidade:'1',valor_unitario:'31.00',data:'2026-09-21',acao:'compra',usuario_id:999});ok(db(`SELECT COUNT(*) FROM investimentos_nacionais WHERE usuario_id=${uid}`)==='2','operação nacional sessão');
 html=await prepare(c,'investimentos_internacionais.php');await post(c,'investimentos_internacionais.php',{csrf:token(html,'csrf'),tipo_ativo:'stock',ticker:'AAPL',quantidade:'1',valor_unitario:'201.00',data:'2026-09-21',acao:'compra',usuario_id:999});ok(db(`SELECT COUNT(*) FROM investimentos_internacionais WHERE usuario_id=${uid}`)==='2','operação internacional sessão');
 // Same OFX bytes and FITID are allowed once per owner.
 html=await prepare(c,'cartao.php');c.ct=token(html,'csrf_cartao');
 const ofx='<OFX><CREDITCARDMSGSRSV1><CCSTMTTRNRS><CCSTMTRS><BANKTRANLIST><STMTTRN><TRNTYPE>DEBIT</TRNTYPE><DTPOSTED>20260921000000</DTPOSTED><TRNAMT>-12.34</TRNAMT><FITID>MULTI-FITID</FITID><NAME>LOJA_TESTE_MULTI</NAME></STMTTRN></BANKTRANLIST></CCSTMTRS></CCSTMTTRNRS></CREDITCARDMSGSRSV1></OFX>';
 const upload=async()=>{const f=new FormData();f.set('mcf_csrf',c.csrf);f.set('csrf_cartao',c.ct);f.set('upload_fatura','1');f.set('usuario_id','999');f.set('fatura',new Blob([ofx]),'fatura-2026-09.ofx');return fetch(base+'/views/cartao.php?mes=9&ano=2026',{method:'POST',headers:{cookie:c.cookie},body:f,redirect:'manual'});};
 ok((await upload()).status===302,'upload OFX');const pi=db(`SELECT id FROM compras WHERE usuario_id=${uid} AND nome='LOJA_TESTE_MULTI'`);ok(!!pi,'compra OFX própria');ok(db(`SELECT COUNT(*) FROM cartoes WHERE usuario_id=${uid} AND compra_id=${pi}`)==='1','parcela OFX própria');await upload();ok(db(`SELECT COUNT(*) FROM compras WHERE usuario_id=${uid} AND nome='LOJA_TESTE_MULTI'`)==='1','OFX idempotente dentro da conta');
 await post(c,'cartao.php',{csrf_cartao:c.ct,renomear_compra:1,compra_id:pi,novo_nome:'NOME_PRIVADO_'+uid,repetir_nome:1});ok(db(`SELECT nome FROM compras WHERE id=${pi}`)==='NOME_PRIVADO_'+uid,'renomear importação');
 ok(db(`SELECT COUNT(*) FROM cartao_nomes_recorrentes WHERE usuario_id=${uid} AND nome_personalizado='NOME_PRIVADO_${uid}'`)==='1','regra recorrente própria');
 await post(c,'cartao.php',{csrf_cartao:c.ct,deletar_cartao:1,compra_id:pi,mes:9,ano:2026});ok(db(`SELECT COUNT(*) FROM compras WHERE id=${pi}`)==='0','excluir compra própria');
}
ok(db("SELECT COUNT(*) FROM corretoras WHERE nome='MESMO_NOME'")==='2','duas corretoras com mesmo nome');ok(db("SELECT COUNT(*) FROM ofx_importacoes WHERE nome_arquivo='fatura-2026-09.ofx'")==='2','mesmo arquivo importado por duas contas');
// Explicitly exercise public account creation, fixation resistance and reset-token non-disclosure.
const fresh=new Client();await fresh.req('/views/login/register.php');const r=await fresh.req('/views/login/register.php',{mcf_csrf:fresh.csrf,nome:'Cadastro Teste',email:'cadastro@example.test',senha:'Cadastro-Teste-2026!',confirmar_senha:'Cadastro-Teste-2026!',usuario_id:1,admin:1});ok(r.status===200&&r.text.includes('Usuário cadastrado com sucesso'),'cadastro independente');const uid=Number(db("SELECT id FROM usuarios WHERE email='cadastro@example.test'"));ok(uid>2,'novo ID');ok(tables.every(t=>db(`SELECT COUNT(*) FROM ${t} WHERE usuario_id=${uid}`)==='0'),'nova conta começa vazia');
const reset=await fresh.req('/views/login/esqueci_senha.php',{mcf_csrf:fresh.csrf,email:'alfa@example.test'});ok(!reset.text.includes('?token='),'recuperação sem revelar token');
for(const p of ['contas.php','rendas.php','cartao.php','saldos.php']){const html=await prepare(a,p);for(const form of html.matchAll(/<form\b[^>]*method="get"[^>]*>([\s\S]*?)<\/form>/gi))ok(!form[1].includes('mcf_csrf'),'filtro GET não envia CSRF na URL');}
console.log(`PASS: ${n} verificações adicionais (CRUD, importação, investimentos, cadastro)`);fs.writeFileSync(path.join(process.env.MCF_TEST_OUTPUT || __dirname,'extended-result.json'),JSON.stringify({passed:n,date:new Date().toISOString()},null,2));
})().catch(e=>{console.error('FAIL',e.message,e.stack);process.exitCode=1;});
