const assert=require('assert/strict'),cp=require('child_process'),fs=require('fs'),path=require('path');
const {Client}=require('./client.cjs');
const db=s=>cp.execFileSync('C:/xampp/mysql/bin/mysql.exe',['-u','root','-N','-B','mcf_test_20260921'],{input:s,encoding:'utf8'}).trim();
let n=0;const ok=(v,m)=>{assert.ok(v,m);n++;};
(async()=>{
 const a=new Client(),b=new Client();await a.login('alfa@example.test');await b.login('beta@example.test');
 const id=Number(db('SELECT id FROM compartilhamentos WHERE proprietario_id=1 AND leitor_id=2'));const version=()=>db('SELECT versao FROM compartilhamentos WHERE id='+id);
 const mods=['despesas','receitas','cartao','saldos','investimentos','daytrade','analise'];
 async function grant(actions){await a.req('/views/compartilhamento.php');const fields={'modulos[0]':'despesas'};mods.forEach((m,i)=>{fields['modulos['+i+']']=m;fields['nivel['+m+']']='edicao';actions.forEach(x=>fields['acoes['+m+']['+x+']']='1');});let r=await a.req('/views/compartilhamento.php',{mcf_csrf:a.csrf,acao:'revisar',id,versao:version(),granular:1,...fields});ok(r.status===303,'revisão granular');await b.req('/views/compartilhamento.php');r=await b.req('/views/compartilhamento.php',{mcf_csrf:b.csrf,acao:'aceitar',id,versao:version()});ok(r.status===303,'aceitação granular');}
 await grant(['cadastrar']);
 ok(db('SELECT COUNT(*) FROM compartilhamento_modulos WHERE compartilhamento_id='+id+' AND cadastrar=1 AND editar=0 AND excluir=0')==='7','sete módulos persistem ações específicas');
 let r=await b.req('/views/contas.php?compartilhamento='+id);ok(r.text.includes('Conta neste módulo')&&r.text.includes('Visão conjunta'),'seletor disponível');
 r=await b.req('/views/trocar_conta.php?modulo=despesas&conta='+id);ok(r.status===303&&r.location.includes('compartilhamento='+id),'seletor valida conta autorizada');
 ok((await a.req('/views/trocar_conta.php?modulo=despesas&conta='+id)).status===404,'titular não usa convite como destinatário');
 ok((await b.req('/views/trocar_conta.php?modulo=despesas&conta=https://evil.test')).status===422,'sem redirecionamento externo');
 r=await b.req('/views/trocar_conta.php?modulo=investimentos&conta=conjunta');ok(r.location.includes('visao_conjunta.php'),'seletor conjunto');
 const post=(p,d)=>b.req('/views/'+p+'?compartilhamento='+id,{mcf_csrf:b.csrf,mcf_contexto:id,mcf_contexto_versao:version(),...d});
 r=await post('contas.php',{nova_conta:1,nomeConta:'AUDIT-TEST',tipoConta:'unica',categoria:'pessoal',vencimento:'2026-09-22',valor:42});ok(r.status===302,'cadastrar sem editar funciona');
 const row=db("SELECT id FROM contas WHERE usuario_id=1 AND nome='AUDIT-TEST'");ok(Boolean(row),'registro pertence ao titular');
 let audit=JSON.parse(db("SELECT depois FROM historico_alteracoes WHERE tabela='contas' AND registro='"+row+"' AND acao='cadastrar'"));ok(Number(audit.valor)===42&&audit.usuario_id===1,'histórico guarda novo valor');
 ok(db("SELECT ator_id FROM historico_alteracoes WHERE tabela='contas' AND registro='"+row+"' AND acao='cadastrar'")==='2','histórico identifica destinatário como autor');
 for(const [p,d] of [['contas.php',{ajustar_valor:1,id:row,novo_valor:100}],['contas.php',{deletar_conta:1,id:row}],['rendas.php',{ajustar_valor:1}],['cartao.php',{atualizar_paga:1}],['saldos.php',{acao:'editar_conta'}],['investimentos_operacoes.php',{acao:'excluir'}],['div_datacom.php',{ajustar_valor:1}],['daytrade/ajustar_operacao.php',{}]])ok((await post(p,d)).status===403,'ação bloqueada antes da escrita '+p);
 ok(db('SELECT valor FROM contas WHERE id='+row)==='42.00','negações preservam valor');
 r=await a.req('/views/historico.php');ok(r.status===200&&r.text.includes('AUDIT-TEST')&&r.text.includes('42'),'titular vê histórico');
 r=await b.req('/views/historico.php?usuario_id=1');ok(!r.text.includes('AUDIT-TEST'),'destinatário não consulta histórico alheio');
 ok((await b.req('/views/historico.php?compartilhamento='+id)).status===403,'contexto não libera histórico');
 r=await b.req('/views/avisos.php');ok(r.text.includes('Permissões aceitas e ativas'),'aviso de mudança');
 r=await b.req('/views/avisos.php',{mcf_csrf:b.csrf,id,versao:version()});ok(r.status===303,'marcar aviso lido');
 ok(db('SELECT versao FROM compartilhamento_vistos WHERE usuario_id=2 AND compartilhamento_id='+id)===version(),'versão vista persistida');
 await grant(['editar']);
 r=await post('contas.php',{ajustar_valor:1,id:row,novo_valor:55,alcance:'somente'});ok(r.status===302,'editar sem cadastrar funciona');
 audit=JSON.parse(db("SELECT antes FROM historico_alteracoes WHERE tabela='contas' AND registro='"+row+"' AND acao='editar' ORDER BY id DESC LIMIT 1"));ok(Number(audit.valor)===42,'edição guarda valor anterior');
 ok((await post('contas.php',{nova_conta:1})).status===403,'cadastro negado para editor');
 await grant(['excluir']);r=await post('contas.php',{deletar_conta:1,id:row,alcance:'somente'});ok(r.status===302,'exclusão independente');
 audit=JSON.parse(db("SELECT antes FROM historico_alteracoes WHERE tabela='contas' AND registro='"+row+"' AND acao='excluir'"));ok(Number(audit.valor)===55,'exclusão preserva dados no histórico');
 r=await b.req('/views/visao_conjunta.php?modulo=investimentos');ok(r.status===200&&r.text.includes('Participação de cada pessoa')&&r.text.includes('Distribuição por ativo')&&r.text.includes('Evolução do custo das posições abertas'),'comparativo completo');ok(r.text.includes('Não representa valor de mercado histórico'),'limite histórico explícito');
 await a.req('/views/compartilhamento.php');await a.req('/views/compartilhamento.php',{mcf_csrf:a.csrf,acao:'revogar',id,versao:version()});
 ok((await b.req('/views/trocar_conta.php?modulo=despesas&conta='+id)).status===404,'revogação bloqueia seletor');
 ok((await b.req('/views/avisos.php')).text.includes('Acesso encerrado'),'revogação gera aviso');
 console.log('PASS: '+n+' verificações de melhorias');fs.writeFileSync(path.join(process.env.MCF_TEST_OUTPUT,'melhorias-result.json'),JSON.stringify({passed:n},null,2));
})().catch(e=>{console.error(e);process.exitCode=1});
