<?php
if(PHP_SAPI!=='cli'&&realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__){http_response_code(404);exit;}
$participacoes=mcfParticipacao($carteira);$evolucao=mcfEvolucao($conn,$pessoas);
?>
<section><h3>Participação de cada pessoa</h3><p>Percentuais calculados separadamente em reais e dólares, apenas entre as pessoas selecionadas.</p><div class="tabela-scroll"><table><thead><tr><th>Pessoa</th><th>Moeda</th><th>Custo</th><th>Participação no custo</th><th>Valor de mercado</th><th>Participação no mercado</th></tr></thead><tbody>
<?php foreach($participacoes as $r): ?><tr><td><?= $e($r['pessoa']['nome']?:$r['pessoa']['email']) ?></td><td><?= $e($r['moeda']) ?></td><td><?= $e($money($r['custo'],$r['moeda'])) ?></td><td><meter min="0" max="100" value="<?= $e($r['percentual_custo']) ?>"></meter> <?= $e(number_format((float)$r['percentual_custo'],2,',','.')) ?>%</td><td><?= $e($money($r['mercado'],$r['moeda'])) ?></td><td><?= $r['percentual_mercado']===null?'Indisponível':$e(number_format((float)$r['percentual_mercado'],2,',','.')).'%' ?></td></tr><?php endforeach; ?>
</tbody></table></div><?php if(!$participacoes): ?><p>Nenhuma posição aberta.</p><?php endif; ?></section>
<section><h3>Distribuição por ativo</h3><p>Participação no custo das posições abertas, por moeda.</p><div class="tabela-scroll"><table><thead><tr><th>Ativo</th><th>Moeda</th><th>Custo</th><th>Participação</th></tr></thead><tbody><?php foreach($carteira['agrupadas'] as $r): $total=$carteira['totais'][$r['moeda']]['custo'];$pct=bccomp($total,'0',12)>0?bcmul(bcdiv($r['custo'],$total,12),'100',4):'0'; ?><tr><td><?= $e($r['ticker'].' · '.$r['tipo']) ?></td><td><?= $e($r['moeda']) ?></td><td><?= $e($money($r['custo'],$r['moeda'])) ?></td><td><meter min="0" max="100" value="<?= $e($pct) ?>"></meter> <?= $e(number_format((float)$pct,2,',','.')) ?>%</td></tr><?php endforeach; ?></tbody></table></div></section>
<section><h3>Evolução do custo das posições abertas</h3><p>Últimos 12 meses: fechamento de cada mês e posição até hoje no mês atual. Compras aumentam o custo; vendas retiram o custo correspondente. Não representa valor de mercado histórico, aportes líquidos ou rentabilidade.</p>
<?php foreach(['BRL','USD'] as $m): $max=1;foreach($evolucao as $r)$max=max($max,(float)$r[$m]['total']);$colors=['#12618a','#9c3c10','#397538','#713b9b','#8a6200']; ?>
<h4><?= $m==='BRL'?'Carteiras em reais':'Carteiras em dólares' ?></h4>
<svg viewBox="0 0 720 220" role="img" aria-label="Evolução do custo em <?= $e($m) ?>; valores exatos na tabela abaixo" style="width:100%;max-height:260px;background:#f5f8fa"><line x1="30" y1="190" x2="690" y2="190" stroke="#777"/><text x="30" y="16" font-size="12"><?= $e($money($max,$m)) ?></text>
<?php $series=['total'=>'#172b3a'];$i=0;foreach($pessoas as $pid=>$p)$series[(string)$pid]=$colors[$i++%count($colors)];foreach($series as $pid=>$color):$points=[];foreach($evolucao as $i=>$r){$value=$pid==='total'?$r[$m]['total']:($r[$m]['pessoas'][(int)$pid]??'0');$points[]=(30+$i*60).','.round(190-160*(float)$value/$max,2);} ?><polyline points="<?= $e(implode(' ',$points)) ?>" fill="none" stroke="<?= $color ?>" stroke-width="<?= $pid==='total'?3:2 ?>"<?= $pid==='total'?' stroke-dasharray="6 3"':'' ?>/><?php endforeach; ?><text x="30" y="212" font-size="12"><?= $e(substr($evolucao[0]['data'],0,7)) ?></text><text x="625" y="212" font-size="12"><?= $e(substr($evolucao[11]['data'],0,7)) ?></text></svg>
<p>Legenda: <strong>Total (linha escura tracejada)</strong><?php $i=0;foreach($pessoas as $p): ?><span style="color:<?= $colors[$i++%count($colors)] ?>"> · <?= $e($p['nome']?:$p['email']) ?></span><?php endforeach; ?></p>
<div class="tabela-scroll"><table><thead><tr><th>Data</th><?php foreach($pessoas as $p): ?><th><?= $e($p['nome']?:$p['email']) ?></th><?php endforeach; ?><th>Total</th></tr></thead><tbody><?php foreach($evolucao as $r): ?><tr><td><?= $e($r['data']) ?></td><?php foreach($pessoas as $pid=>$p): ?><td><?= $e($money($r[$m]['pessoas'][$pid]??'0',$m)) ?></td><?php endforeach; ?><td><?= $e($money($r[$m]['total'],$m)) ?></td></tr><?php endforeach; ?></tbody></table></div>
<?php endforeach; ?></section>
